name: Triggered Tests

on:
  repository_dispatch:
    types: [front-update]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: Run tests
        run: ./gradlew test # Adjust this command to your project's needs